### ISSUE TITLE
Convenience Scripts

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/regtest#10]
To quote yourself:
> i think we should still have a docker-scripts.sh which has convenience functions for lncli etc that are just run in the scripts container

**Comment by dni** [comment]
i think all those scripts could be exucted inside the scripts container
```
docker exec -it regtest-scripts-1
```
its linked into the profile. https://github.com/BoltzExchange/regtest/blob/main/images/scripts/Dockerfile#L27
